stages:
  - "test"
  - "build"

test:
  image: node:latest
  tags:
    - cdp-vue-share
  before_script:
    - mkdir public/js
    - touch public/js/system_config.js
    - cp -r "build_config/system_config_dev.js" "./public/js/system_config.js"
  stage: test
  script:
    - echo "npm run coverage" 
    # - npm i
    # - npm run coverage

dev-build:
  stage: build
  tags:
    - cdp-vue-share  
  image: google/cloud-sdk:latest
  script:    
    - gcloud auth activate-service-account --key-file=$SA_TOKEN_CDP
    - gcloud config set project $PROJECTID_CDP
    - gcloud builds submit --region="us-central1" --config=".cloudbuild/dev-cdp-vue-frontend.yaml" --substitutions _PROCTIME=$(date +"%m%d-%H%M") .  
  after_script:
    - cat public/js/system_config.js | grep --color "build_env_config"
  rules:
    - if: ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push")
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
