stages:
  - "test"
  - "build"

test:
  image: node:latest
  tags:
    - cdp-vue-share
  stage: test
  script:
    - npm install -g vitest
    - npm run test:unit
    - npm run coverage

dev-build:
  stage: build
  tags:
    - cdp-vue-share
  image: google/cloud-sdk:latest
  script:    
    - gcloud auth activate-service-account --key-file=$SA_TOKEN_CDP
    - gcloud config set project $PROJECTID_CDP
    - gcloud builds submit --region="asia-northeast1" --config=".cloudbuild/dev-cdp-vue-frontend.yaml" --substitutions _PROCTIME=$(date +"%m%d-%H%M") .  
  rules:
    - if: ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "push")
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
