substitutions:
  _IMAGEPATH: 'us-central1-docker.pkg.dev/gcp-20190903-01/cdp-backend-images/cdp_backend_vue'  
  _ENVTYPE: 'dev'
  _SERVICE: 'dev-cdp-vue-frontend'
  _SERVICEREGION: 'us-central1'

steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', 'build_config/system_config_${_ENVTYPE}.js', './public/js']

  - name: "ubuntu"
    args: ["bash", "-c", 'echo "_IMAGEPATH= ${_IMAGEPATH}:${_ENVTYPE}_${_PROCTIME}"']

  - name: "ubuntu"
    args: ["bash", "-c", 'echo "[Build-Time] ${_PROCTIME}\r\n [Build-Env] ${_ENVTYPE}\r\n" > release.txt']

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'    
      - 'docker build -t ${_IMAGEPATH}:${_ENVTYPE}_${_PROCTIME}  -t ${_IMAGEPATH}:${_ENVTYPE} .'

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGEPATH}:${_ENVTYPE}_${_PROCTIME}"]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGEPATH}:${_ENVTYPE}"]

  # Deploy To Google Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["run", "deploy", "${_SERVICE}", "--image", "${_IMAGEPATH}:${_ENVTYPE}_${_PROCTIME}", "--region", "${_SERVICEREGION}"]

images:
  - ${_IMAGEPATH}:${_ENVTYPE}_${_PROCTIME}

options:
  logging: CLOUD_LOGGING_ONLY
